"""Generate pgfplots coordinates for the solution family of x' = |x|^(2/3) + x^2.

Each branch is x_T(t) = 0 on [0,T] and phi(t-T) afterwards, where phi = F^{-1}
and F(x) = int_0^x du/f(u).  F is never inverted numerically: we sample x and
emit the point (T + F(x), x), which traces the same curve.

The substitution u = v^3 of sec. 2 turns F into

    F(x) = 3 * int_0^{x^(1/3)} dv/(1+v^4),

whose integrand is smooth over the whole range -- the singularity at the origin
is an artefact of the u-variable, and removing it is what makes this cheap.

The blow-up time T* = 3*sqrt(2)*pi/4 quoted in the text is analytic and does not
depend on this file.  Output: figure-branches.tex.
"""
import mpmath as mp

mp.mp.dps = 25

F     = lambda x: 3*mp.quad(lambda v: 1/(1 + v**4), [0, mp.cbrt(x)])
TSTAR = 3*mp.sqrt(2)*mp.pi/4
CEIL  = mp.mpf(6)                      # graphical cut-off, x = 6

# Consistency: the substituted F agrees with the raw integral, and the
# substituted total agrees with the closed form asserted in the text.
raw = mp.quad(lambda u: 1/(u**(mp.mpf(2)/3) + u**2), [0, mp.mpf('1e-9'), 1, 2])
assert abs(F(mp.mpf(2)) - raw) < mp.mpf('1e-12'), "substitution disagrees with raw integral"
assert abs(3*mp.quad(lambda v: 1/(1 + v**4), [0, mp.inf]) - TSTAR) < mp.mpf('1e-20'), \
    "total disagrees with 3*sqrt(2)*pi/4"

# Sample x with a power law so the near-vertical top of each curve stays smooth.
N    = 240
xs   = [CEIL*(mp.mpf(i)/N)**mp.mpf('2.2') for i in range(N + 1)]
base = [(F(x), x) for x in xs]         # (time since departure, height)

lines = []
for T in ['0', '1.6', '3.2', '4.8']:
    T    = mp.mpf(T)
    pts  = ([(mp.mpf(0), mp.mpf(0))] if T > 0 else []) + [(T + s, x) for s, x in base]
    body = " ".join(f"({mp.nstr(t, 7)},{mp.nstr(x, 7)})" for t, x in pts)
    lines.append(f"\\addplot[branch] coordinates {{{body}}};")

with open('figure-branches.tex', 'w') as fh:
    fh.write("% generated by make_figure_data.py -- do not edit by hand\n")
    fh.write("\n".join(lines) + "\n")

print("T*   =", mp.nstr(TSTAR, 12))
print("F(6) =", mp.nstr(F(CEIL), 12), "(time from the origin to the graphical ceiling)")
print("branches:", len(lines), "| both consistency assertions passed")
